{
	"version": 1580374286,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/block.png",
		"images/player-sheet0.png",
		"images/respawn-sheet0.png",
		"images/homebutton-sheet0.png",
		"images/buttonlevel1-sheet0.png",
		"images/buttonlevel2-sheet0.png",
		"images/buttonlevel3-sheet0.png",
		"images/quit-sheet0.png",
		"images/dubblejump-sheet0.png",
		"images/speed-sheet0.png",
		"images/dubblejumptrapoff-sheet0.png",
		"images/deathtrap-sheet0.png",
		"images/openportal-sheet0.png",
		"images/portal-sheet0.png",
		"images/bullet-sheet0.png",
		"images/spear-sheet0.png",
		"images/spearenemy-sheet0.png",
		"images/spearenemy-sheet1.png",
		"images/enemyguard-sheet0.png",
		"images/enemyguard-sheet1.png",
		"images/enemyguard-sheet2.png",
		"images/enemyguard-sheet3.png",
		"images/enemyguard-sheet4.png",
		"images/enemyguard-sheet5.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/backgroundscreen-sheet0.png",
		"images/animation-sheet0.png",
		"images/animation-sheet1.png",
		"media/free logic  kyle type beat super mario (ft. lil yachty)  2019 instrumental.m4a",
		"media/free logic  kyle type beat super mario (ft. lil yachty)  2019 instrumental.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}